services:
  - type: web
    name: mediatek-symfony
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: 0
      - key: DATABASE_URL
        value: mysql://411497:Mediatek10@mysql-mediate-formation.alwaysdata.net:3306/mediate-formation-sql?serverVersion=mariadb-10.11## YAML Template.
---
